item { 
	id:1
	name:'Player Bar'
}
item { 
	id:2
	name:'Stats Display'
}
item { 
	id:3
	name:'Team Display'
}
item { 
	id:4
	name:'Mini Map'
}
item { 
	id:5
	name:'Enemy Display'
}
